### ISSUE TITLE
UMMM Suddenly Producing Bad Manifests with RichTx32.ocx

### ISSUE THREAD

**Issue by jpbro** [wqweto/UMMM#30]
I'm not sure if this is a UMMM problem, or a problem with my machine, so please excuse me if it's a "me" problem.

In the past day or so, UMMM has been producing bad manifests with the following warning:

`Result: warning: ProgID RICHTEXT.RichtextCtrl already used for CLSID {3B7C8860-D78F-101B-B9B5-04021C009402} ({894BA3A3-3CA3-402F-B4FE-CD08337E9535})warning: ProgID RICHTEXT.RichtextCtrl.1 already used for CLSID {3B7C8860-D78F-101B-B9B5-04021C009402} ({894BA3A3-3CA3-402F-B4FE-CD08337E9535})
`

The manifest entry it produces for RichTx32.ocx looks like this:

```
    <file name="Tools\Libraries\RichTx32.ocx">
        <typelib tlbid="{3B7C8863-D78F-101B-B9B5-04021C009402}" version="1.2" flags="control,hasdiskimage" helpdir="" />
        <comClass clsid="{3B7C8860-D78F-101B-B9B5-04021C009402}" tlbid="{3B7C8863-D78F-101B-B9B5-04021C009402}" progid="RICHTEXT.RichtextCtrl.1" threadingModel="Apartment" miscStatus="" miscStatusContent="recomposeonresize,cantlinkinside,insideout,activatewhenvisible,setclientsitefirst">
            <progid>RICHTEXT.RichtextCtrl</progid>
        </comClass>
        <comClass clsid="{894BA3A3-3CA3-402F-B4FE-CD08337E9535}" tlbid="{3B7C8863-D78F-101B-B9B5-04021C009402}" threadingModel="Apartment" miscStatus="" miscStatusContent="recomposeonresize,cantlinkinside,insideout,activatewhenvisible,setclientsitefirst" />
    </file>
```	

Whereas it used to look like this a couple of days ago with the working manifest:

```
    <file name="Tools\Libraries\RichTx32.ocx">
        <typelib tlbid="{3B7C8863-D78F-101B-B9B5-04021C009402}" version="1.2" flags="control,hasdiskimage" helpdir="" />
        <comClass clsid="{3B7C8860-D78F-101B-B9B5-04021C009402}" tlbid="{3B7C8863-D78F-101B-B9B5-04021C009402}" progid="RICHTEXT.RichtextCtrl" threadingModel="Apartment" miscStatus="" miscStatusContent="recomposeonresize,cantlinkinside,insideout,activatewhenvisible,setclientsitefirst" />
    </file>
```

The part that has me unsure if the problem is mine is that even manually editing the manifest so that it uses the old RichTx32.ocx block still produces an SxS error when I try to run the EXE with the manifest. The error I'm getting when trying to run the EXE with the bad manifest is as follows:

`The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.`

Neither sxstrace.exe nor the application event log give any clue as to what is wrong with the manifest other than saying "ERROR: Activation Context generation failed."

I've tried unregistering and re-registering RichTx32.ocx, but there's no change to the problem.

Do you have any thoughts as to what might be going wrong? Thank you for any help!

**Comment by wqweto** [comment]
It looks like you have two OCX files with different versions of RichTextBox control registered and/or referenced in the `ini` file.

Try to lookup COM server location (the OCX file) for both `{3B7C8860-D78F-101B-B9B5-04021C009402}` and  `{894BA3A3-3CA3-402F-B4FE-CD08337E9535}` CLSIDs in the (32-bit) registry.

**Comment by jpbro** [comment]
Thanks for taking a look. I think something must be messed up on my machine. When I unregister all references to the RichTx32.ocx are properly removed from the registry, but re-registering always brings back the .1 variant. Anyway it's definitely not UMMM's problem, so I will close this issue. Sorry for the bother!

**Comment by jpbro** [comment]
OMG I finally figured out what was wrong. The warning about RichTx32.ocx was a red-herring, I guess I just never noticed that warning before and thought it was related to the SxS error I was suddenly seeing. Instead I somehow saved my .ini file with a Tab after "win10" in a SupportedOS directive, and this was causing "win10<tab>" to appear in the manifest instead of a proper GUID. It's often the dumbest things that we end up throwing a day away on!

**Comment by wqweto** [comment]
I decided to add as collaborator anyone who is submitting PRs to any of my open-source repos.

The reason is that if someone cares to enhance the project it will be much easier and smooth to do so and I certainly don't want to be the "guardian of the codebase" :-))

Next time you can merge changes with or without discussion here.

**Comment by jpbro** [comment]
Thank you! I will treat the codebase respectfully :)
