### ISSUE TITLE
Manifest output file issue

### ISSUE THREAD

**Issue by surfer-silver** [wqweto/UMMM#37]
output manifest file needs to realign the size everytime or it will crash the app.
so what i do to change size that matches filesize mod 4 = 0. 
if possible please change in your next release.

**Comment by wqweto** [comment]
Size **padding** (not alignment) is done by resource embedding tool, not manifest creator tool. This means that `mt.exe` will pad the resource as needed.

Besides you can always manually pad the XML file with spaces if you need to for whatever other reason.

**Comment by surfer-silver** [comment]
you are awesome ! 
i was facing another also but resolved by reading this 
https://github.com/wqweto/UMMM/issues/30
thank you so much for your prompt help
