### ISSUE TITLE
TrustInfo Parameters Error?

### ISSUE THREAD

**Issue by jpbro** [wqweto/UMMM#8]
First off, thanks for creating this tool! It is very useful as part of my automated build process.

The documentation states that the first parameter (level) should be 1 for asInvoker, 2 for highestAvailable, and 3 for requireAdministrator, however it appears that it should in fact be 0 for asInvoker, 1 for highestAvailable, and 2 for requireAdministrator since the related code uses the Array() function which returns a 0-based array:

_Array("asInvoker", "highestAvailable", "requireAdministrator")(lLevel)_

My tests back this up (just tried setting the level parameter to 1 for asInvoker but the resultant binary requested elevation).

**Comment by wqweto** [comment]
10x, will take a look at this

**Comment by wqweto** [comment]
82ecdb2ad3f0509c0f54b1e8d0794790884608a2 should fix this off by one error
